apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 3-tier-cbc
  region: ap-southeast-1

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"

vpc:
  subnets:
    private:
      frontend:
        id: subnet-09ce085f9d58c82d7
        id: subnet-080cf9bb5a360c95c
      backend:
        id: subnet-00a3849e2ea94267d
        id: subnet-0a32b2419e7c65627

managedNodeGroups:
- name: frontend
  instanceType: m5.large
  labels: { role: frontend }
  desiredCapacity: 1
  privateNetworking: true
  subnets:
    - frontend
- name: backend
  instanceType: m5.large
  labels: { role: backend }
  desiredCapacity: 1
  privateNetworking: true
  subnets:
    - backend