apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend 
  ports:
    - name: "http"
      port: 80
      targetPort: 5001 
      nodePort: 31080 