apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-cluster1-cbc
  region: ap-southeast-1

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"

vpc:
  subnets:
    private:
      ap-southeast-1a:
        id: subnet-0a7c019b390586252
      ap-southeast-1b:
        id: subnet-02f459413f19ca4a9


managedNodeGroups:
- name: frontend
  instanceType: m5.large
  labels: { role: frontend }
  desiredCapacity: 2
  privateNetworking: true
  subnets:
  - subnet-080cf9bb5a360c95c
  - subnet-09ce085f9d58c82d7
- name: backend
  instanceType: m5.large
  labels: { role: backend }
  desiredCapacity: 2
  privateNetworking: true
  subnets:
   - subnet-00a3849e2ea94267d
   - subnet-0a32b2419e7c65627