apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-cluster-cbc
  region: ap-southeast-1

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"

vpc:
  subnets:
    private:
      ap-southeast-1a:
        id: subnet-0a7c019b390586252
      ap-southeast-1b:
        id: subnet-02f459413f19ca4a9


managedNodeGroups:
- name: frontend
  instanceType: m5.large
  labels: { role: frontend }
  desiredCapacity: 1
  privateNetworking: true
- name: backend
  instanceType: m5.large
  labels: { role: backend }
  desiredCapacity: 1
  privateNetworking: true
- name: subnets
  desiredCapacity: 1
  ssh: # import public key from file
    publicKeyPath: ~/.ssh/id_rsa.pub
  subnets:
  - subnet-0f7e27a57f2a635a3